<script lang="ts">
  import { onMount } from 'svelte';
  let { user, onVerified, onSignout }: { user: User; onVerified: (user: User) => void; onSignout: () => void } = $props();
  let busy = $state(false); let message = $state(''); let stopped = false;
  async function check(resend = false) { if (busy || stopped) return; busy = true; message = ''; try { const result = await window.marioNet!.verification(resend); if (result.ok && result.emailVerified) { onVerified({ ...user, emailVerified: true }); return; } if (resend) message = '인증 메일을 다시 보냈어요. 받은편지함과 스팸함을 확인해주세요.'; else if (!result.ok) message = result.code === 'RATE_LIMITED' ? '요청이 많아요. 잠시 후 다시 시도해주세요.' : '인증 상태를 확인하지 못했어요.'; } catch { if (!stopped) message = '서버에 연결하지 못했어요. 잠시 후 다시 시도해주세요.'; } finally { busy = false; } }
  onMount(() => { void check(true); const timer = setInterval(() => void check(), 2500); return () => { stopped = true; clearInterval(timer); }; });
</script>
<section class="verification-wait" aria-labelledby="verification-title"><div class="verification-card"><div class="mail-mark" aria-hidden="true">✉</div><p class="eyebrow">EMAIL VERIFICATION</p><h1 id="verification-title">이메일 인증을 기다리고 있어요</h1><p class="copy"><strong>{user.email}</strong>로 보낸 인증 링크를 클릭해주세요.<br />인증이 끝나면 이 화면이 자동으로 홈으로 바뀝니다.</p><div class="waiting" role="status"><span class="spinner"></span>인증 상태 확인 중</div>{#if message}<p class="message" role="alert">{message}</p>{/if}<button class="resend" disabled={busy} onclick={() => check(true)}>인증 메일 다시 보내기</button><button class="back" disabled={busy} onclick={onSignout}>로그아웃</button></div></section>
<style>
 .verification-wait{min-height:100svh;background:#171727;display:grid;place-items:center;padding:84px 30px 40px}.verification-card{width:min(100%,480px);background:#24263d;border:1px solid #ffffff0d;border-radius:24px;padding:44px;text-align:center}.mail-mark{width:62px;height:62px;display:grid;place-items:center;margin:0 auto 28px;border-radius:20px;background:#2864ef20;color:#83a7ff;font-size:27px}.eyebrow{font-size:9px;letter-spacing:1.7px;color:#8c9ac1;margin:0 0 13px}.verification-card h1{font-size:25px;letter-spacing:-1px;margin:0}.copy{color:#aeb6d0;font-size:13px;line-height:1.9;margin:18px 0 28px}.copy strong{color:#f1f4ff;font-weight:600;overflow-wrap:anywhere}.waiting{display:flex;align-items:center;justify-content:center;gap:9px;background:#191a2b;border-radius:11px;padding:13px;color:#b7c5e8;font-size:12px}.spinner{display:block;width:14px;height:14px;border:2px solid #ffffff40;border-top-color:#7fa6ff;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.message{color:#ffabb6;font-size:12px;line-height:1.7}.resend,.back{width:100%;min-height:44px;border:0;border-radius:12px;font-size:13px;font-weight:650}.resend{margin-top:22px;background:#2864ef;color:#fff}.back{margin-top:10px;background:transparent;color:#aeb6d0}.resend:disabled,.back:disabled{opacity:.5}
</style>
